server {
    listen 8080;

    location / {
        proxy_pass http://127.0.0.1:8081/;
    }

    location /img/ {
        proxy_pass http://127.0.0.1:8082/;
    }

    location ~ \.js {
        proxy_pass http://127.0.0.1:8083;
    }
}

server {
    listen 8081;

    root %%nginxROOTDIR%%/default;
}

server {
    listen 8082;

    root %%nginxROOTDIR%%/images;
}

server {
    listen 8083;

    root %%nginxROOTDIR%%/scripts;
}
