server {
  listen 81;
  server_name localhost;
  root /var/www/rhts-nginx-root;

  location /rp/ {
     proxy_pass       http://127.0.0.1:81/;
     proxy_set_header Host      $host;
     proxy_set_header  X-Real-IP $remote_addr;
  }
}
