server {
  listen 81;
  server_name localhost;
  root /var/www/rhts-nginx-root;

  location ~ \.php$ {
    include        fastcgi_params;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME /var/www/rhts-nginx-root$fastcgi_script_name;
  }
}
