server {
    listen 80;
    server_name www.app4000.com;

    # Tells Nginx to serve static assets from this directory.
    root %%nginxROOTPREFIX%%/usr/share/nginx/app4000/public;

    location / {
        proxy_pass http://127.0.0.1:4000;
    }
}

server {
    listen 80;
    server_name www.app4001.com;

    # Tells Nginx to serve static assets from this directory.
    root %%nginxROOTPREFIX%%/usr/share/nginx/app4001/public;

    location / {
        proxy_pass http://127.0.0.1:4001;
    }
}

server {
    listen 80;
    server_name www.app4002.com;

    # Tells Nginx to serve static assets from this directory.
    root %%nginxROOTPREFIX%%/usr/share/nginx/app4002/public;

    location / {
        proxy_pass http://127.0.0.1:4002;
    }
}

